# Generated by Django 5.2.3 on 2025-06-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_artwork_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='published_at',
            new_name='published_date',
        ),
    ]
