# Generated by Django 5.2.3 on 2025-06-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_artwork_likes_count_artwork_price_artwork_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='tags',
        ),
    ]
